os161-doc: /home/parallels/os161/os161-base-2.0.3/kern/test/semunit.c File Reference
semunit.c File Reference
#include <types.h>
#include <lib.h>
#include <spinlock.h>
#include <synch.h>
#include <thread.h>
#include <current.h>
#include <clock.h>
#include <test.h>
Macros
#define NAMESTRING "some-silly-name"
Functions
static void ok (void)
static struct semaphore * makesem (unsigned count)
static void waiter (void *vsem, unsigned long junk)
static void makewaiter (struct semaphore *sem)
static bool spinlock_not_held (struct spinlock *splk)
int semu1 (int nargs, char **args)
int semu2 (int nargs, char **args)
int semu3 (int nargs, char **args)
int semu4 (int nargs, char **args)
int semu5 (int nargs, char **args)
int semu6 (int nargs, char **args)
int semu7 (int nargs, char **args)
static void do_semu89 (bool interrupthandler)
int semu8 (int nargs, char **args)
int semu9 (int nargs, char **args)
static int do_semu1011 (bool interrupthandler)
int semu10 (int nargs, char **args)
int semu11 (int nargs, char **args)
static void semu1213 (bool interrupthandler)
int semu12 (int nargs, char **args)
int semu13 (int nargs, char **args)
int semu14 (int nargs, char **args)
int semu15 (int nargs, char **args)
int semu16 (int nargs, char **args)
static void semu17_sub (void *semv, unsigned long junk)
int semu17 (int nargs, char **args)
int semu18 (int nargs, char **args)
static void semu19_sub (void *semv, unsigned long junk)
int semu19 (int nargs, char **args)
int semu20 (int nargs, char **args)
int semu21 (int nargs, char **args)
int semu22 (int nargs, char **args)
Variables
static unsigned waiters_running = 0
static struct spinlock waiters_lock = SPINLOCK_INITIALIZER
static struct thread * semu17_thread
Macro Definition Documentation
NAMESTRING
#define NAMESTRING "some-silly-name"
Definition at line 56 of file semunit.c.
Function Documentation
do_semu1011()
static int do_semu1011 (bool interrupthandler) static
Definition at line 397 of file semunit.c.
References clocksleep(), KASSERT, makesem(), makewaiter(), name, NAMESTRING, ok(), semaphore::sem_count, sem_destroy(), semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_acquire(), spinlock_not_held(), spinlock_release(), strcmp(), V(), waiters_lock, and waiters_running.
Referenced by semu10(), and semu11().
do_semu89()
static void do_semu89 (bool interrupthandler) static
Definition at line 320 of file semunit.c.
References KASSERT, makesem(), name, NAMESTRING, ok(), semaphore::sem_count, sem_destroy(), semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_not_held(), strcmp(), and V().
Referenced by semu8(), and semu9().
makesem()
static struct semaphore * makesem (unsigned count) static
Definition at line 76 of file semunit.c.
References count, NAMESTRING, NULL, panic(), and sem_create().
Referenced by do_semu1011(), do_semu89(), semu1213(), semu14(), semu16(), semu17(), semu18(), semu19(), semu20(), semu21(), semu4(), semu6(), and semu7().
makewaiter()
static void makewaiter (struct semaphore * sem) static
Definition at line 110 of file semunit.c.
References clocksleep(), kprintf(), NULL, panic(), spinlock_acquire(), spinlock_release(), thread_fork(), waiter(), waiters_lock, and waiters_running.
Referenced by do_semu1011(), semu1213(), and semu6().
ok()
static void ok (void) static
Definition at line 66 of file semunit.c.
References kprintf().
Referenced by do_semu1011(), do_semu89(), report_check2(), report_check3(), runop(), semu1(), semu1213(), semu16(), semu17(), semu4(), semu5(), and semu7().
semu1()
int semu1 (int nargs, char ** args)
Definition at line 155 of file semunit.c.
References KASSERT, name, NAMESTRING, NULL, ok(), panic(), semaphore::sem_count, sem_create(), sem_destroy(), semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_not_held(), and strcmp().
semu10()
int semu10 (int nargs, char ** args)
Definition at line 449 of file semunit.c.
References do_semu1011().
semu11()
int semu11 (int nargs, char ** args)
Definition at line 458 of file semunit.c.
References do_semu1011().
semu12()
int semu12 (int nargs, char ** args)
Definition at line 536 of file semunit.c.
References semu1213().
semu1213()
static void semu1213 (bool interrupthandler) static
Definition at line 479 of file semunit.c.
References clocksleep(), KASSERT, makesem(), makewaiter(), name, NAMESTRING, ok(), semaphore::sem_count, sem_destroy(), semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_acquire(), spinlock_not_held(), spinlock_release(), strcmp(), V(), waiters_lock, and waiters_running.
Referenced by semu12(), and semu13().
semu13()
int semu13 (int nargs, char ** args)
Definition at line 545 of file semunit.c.
References semu1213().
semu14()
int semu14 (int nargs, char ** args)
Definition at line 558 of file semunit.c.
References KASSERT, kprintf(), makesem(), panic(), semaphore::sem_count, and V().
semu15()
int semu15 (int nargs, char ** args)
Definition at line 582 of file semunit.c.
References kprintf(), NULL, panic(), and V().
semu16()
int semu16 (int nargs, char ** args)
Definition at line 596 of file semunit.c.
References makesem(), ok(), P(), sem_destroy(), spinlock_acquire(), spinlock_cleanup(), spinlock_init(), and spinlock_release().
semu17()
int semu17 (int nargs, char ** args)
Definition at line 641 of file semunit.c.
References clocksleep(), KASSERT, kprintf(), makesem(), NULL, ok(), panic(), S_SLEEP, sem_destroy(), semu17_sub(), semu17_thread, thread::t_state, thread_fork(), and V().
semu17_sub()
static void semu17_sub (void * semv, unsigned long junk) static
Definition at line 626 of file semunit.c.
References KASSERT, P(), semaphore::sem_count, and semu17_thread.
Referenced by semu17().
semu18()
int semu18 (int nargs, char ** args)
Definition at line 679 of file semunit.c.
References KASSERT, makesem(), name, NAMESTRING, P(), semaphore::sem_count, semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, spinlock_not_held(), and strcmp().
semu19()
int semu19 (int nargs, char ** args)
Definition at line 736 of file semunit.c.
References KASSERT, makesem(), name, NAMESTRING, NULL, P(), panic(), semaphore::sem_count, semaphore::sem_lock, semaphore::sem_name, semaphore::sem_wchan, semu19_sub(), spinlock_not_held(), strcmp(), and thread_fork().
semu19_sub()
static void semu19_sub (void * semv, unsigned long junk) static
Definition at line 719 of file semunit.c.
References clocksleep(), kprintf(), and V().
Referenced by semu19().
semu2()
int semu2 (int nargs, char ** args)
Definition at line 182 of file semunit.c.
References kprintf(), NULL, panic(), and sem_create().
semu20()
int semu20 (int nargs, char ** args)
Definition at line 775 of file semunit.c.
References kprintf(), makesem(), P(), and panic().
semu21()
int semu21 (int nargs, char ** args)
Definition at line 792 of file semunit.c.
References kprintf(), makesem(), P(), and panic().
semu22()
int semu22 (int nargs, char ** args)
Definition at line 812 of file semunit.c.
References kprintf(), NULL, P(), and panic().
semu3()
int semu3 (int nargs, char ** args)
Definition at line 199 of file semunit.c.
References kprintf(), NULL, panic(), and sem_destroy().
semu4()
int semu4 (int nargs, char ** args)
Definition at line 213 of file semunit.c.
References KASSERT, makesem(), ok(), semaphore::sem_count, and sem_destroy().
semu5()
int semu5 (int nargs, char ** args)
Definition at line 237 of file semunit.c.
References KASSERT, NAMESTRING, NULL, ok(), panic(), semaphore::sem_count, sem_create(), and sem_destroy().
semu6()
int semu6 (int nargs, char ** args)
Definition at line 261 of file semunit.c.
References kprintf(), makesem(), makewaiter(), panic(), and sem_destroy().
semu7()
int semu7 (int nargs, char ** args)
Definition at line 280 of file semunit.c.
References makesem(), ok(), sem_destroy(), spinlock_acquire(), spinlock_cleanup(), spinlock_init(), spinlock_release(), and V().
semu8()
int semu8 (int nargs, char ** args)
Definition at line 367 of file semunit.c.
References do_semu89().
semu9()
int semu9 (int nargs, char ** args)
Definition at line 376 of file semunit.c.
References do_semu89().
spinlock_not_held()
static bool spinlock_not_held (struct spinlock * splk) static
Definition at line 138 of file semunit.c.
References NULL, and spinlock::splk_holder.
Referenced by do_semu1011(), do_semu89(), semu1(), semu1213(), semu18(), and semu19().
waiter()
static void waiter (void * vsem, unsigned long junk) static
Definition at line 92 of file semunit.c.
References KASSERT, P(), spinlock_acquire(), spinlock_release(), waiters_lock, and waiters_running.
Referenced by makewaiter().
Variable Documentation
semu17_thread
struct thread* semu17_thread static
Definition at line 622 of file semunit.c.
Referenced by semu17(), and semu17_sub().
waiters_lock
struct spinlock waiters_lock = SPINLOCK_INITIALIZER static
Definition at line 62 of file semunit.c.
Referenced by do_semu1011(), makewaiter(), semu1213(), and waiter().
waiters_running
unsigned waiters_running = 0 static
Definition at line 61 of file semunit.c.
Referenced by do_semu1011(), makewaiter(), semu1213(), and waiter().