os161-doc: buftest Struct Reference
buftest Struct Reference
Data Fields
int(* setup)(void)
int(* op)(void *)
void(* cleanup)(void)
const char * name
Detailed Description
Definition at line 49 of file common_buf.c.
Field Documentation
cleanup
void(* cleanup) (void)
Definition at line 52 of file common_buf.c.
Referenced by common_badbuf().
name
const char* name
Definition at line 53 of file common_buf.c.
Referenced by common_badbuf().
op
int(* op) (void *)
Definition at line 51 of file common_buf.c.
Referenced by common_badbuf().
setup
int(* setup) (void)
Definition at line 50 of file common_buf.c.
Referenced by common_badbuf().
The documentation for this struct was generated from the following file:
/home/parallels/os161/os161-base-2.0.3/userland/testbin/badcall/common_buf.c