os161-doc: /home/parallels/os161/os161-base-2.0.3/userland/lib/libc/stdlib/malloc.c File Reference
malloc.c File Reference
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include <err.h>
#include <assert.h>
Data Structures
struct mheader
Macros
#define M_NEXTOFF(mh) ((size_t)(((size_t)((mh)->mh_nextblock))<<MBLOCKSHIFT))
#define M_PREVOFF(mh) ((size_t)(((size_t)((mh)->mh_prevblock))<<MBLOCKSHIFT))
#define M_NEXT(mh) ((struct mheader *)(((char*)(mh))+M_NEXTOFF(mh)))
#define M_PREV(mh) ((struct mheader *)(((char*)(mh))-M_PREVOFF(mh)))
#define M_DATA(mh) ((void *)((mh)+1))
#define M_SIZE(mh) (M_NEXTOFF(mh)-MBLOCKSIZE)
#define M_OK(mh) ((mh)->mh_magic1==MMAGIC && (mh)->mh_magic2==MMAGIC)
#define M_MKFIELD(off) ((off)>>MBLOCKSHIFT)
#define PAGE_SIZE 4096
Functions
static void __malloc_init (void)
static void * __malloc_sbrk (size_t size)
static void __malloc_split (struct mheader *mh, size_t size)
void * malloc (size_t size)
static void __malloc_deadbeef (void *ptr, size_t size)
static void __malloc_trymerge (struct mheader *mh, struct mheader *mhnext)
void free (void *x)
Variables
static uintptr_t __heapbase
static uintptr_t __heaptop
Macro Definition Documentation
M_DATA
#define M_DATA (mh) ((void *)((mh)+1))
Definition at line 130 of file malloc.c.
M_MKFIELD
#define M_MKFIELD (off) ((off)>>MBLOCKSHIFT)
Definition at line 135 of file malloc.c.
M_NEXT
#define M_NEXT (mh) ((struct mheader *)(((char*)(mh))+M_NEXTOFF(mh)))
Definition at line 127 of file malloc.c.
M_NEXTOFF
#define M_NEXTOFF (mh) ((size_t)(((size_t)((mh)->mh_nextblock))<<MBLOCKSHIFT))
Definition at line 125 of file malloc.c.
M_OK
#define M_OK (mh) ((mh)->mh_magic1==MMAGIC && (mh)->mh_magic2==MMAGIC)
Definition at line 133 of file malloc.c.
M_PREV
#define M_PREV (mh) ((struct mheader *)(((char*)(mh))-M_PREVOFF(mh)))
Definition at line 128 of file malloc.c.
M_PREVOFF
#define M_PREVOFF (mh) ((size_t)(((size_t)((mh)->mh_prevblock))<<MBLOCKSHIFT))
Definition at line 126 of file malloc.c.
M_SIZE
#define M_SIZE (mh) (M_NEXTOFF(mh)-MBLOCKSIZE)
Definition at line 131 of file malloc.c.
PAGE_SIZE
#define PAGE_SIZE 4096
Definition at line 147 of file malloc.c.
Function Documentation
__malloc_deadbeef()
static void __malloc_deadbeef (void * ptr, size_t size) static
Definition at line 490 of file malloc.c.
Referenced by __malloc_trymerge(), and free().
__malloc_init()
static void __malloc_init (void) static
Definition at line 162 of file malloc.c.
References __heapbase, __heaptop, err(), errx(), sbrk(), and warnx().
Referenced by malloc().
__malloc_sbrk()
static void * __malloc_sbrk (size_t size) static
Definition at line 282 of file malloc.c.
References __heaptop, errx(), NULL, and sbrk().
Referenced by malloc().
__malloc_split()
static void __malloc_split (struct mheader * mh, size_t size) static
Definition at line 311 of file malloc.c.
References __heaptop, errx(), M_MKFIELD, M_NEXT, and M_SIZE.
Referenced by malloc().
__malloc_trymerge()
static void __malloc_trymerge (struct mheader * mh, struct mheader * mhnext) static
Definition at line 504 of file malloc.c.
References __heaptop, __malloc_deadbeef(), errx(), M_MKFIELD, M_NEXT, and M_SIZE.
Referenced by free().
free()
void free (void * x)
Definition at line 534 of file malloc.c.
References __heapbase, __heaptop, __malloc_deadbeef(), __malloc_trymerge(), errx(), M_DATA, M_NEXT, M_OK, M_PREV, M_SIZE, NULL, and warnx().
Referenced by dorealloc(), pass1_dir(), pass2_dir(), test1(), test2(), test3(), test4(), and test567().
malloc()
void * malloc (size_t size)
Definition at line 352 of file malloc.c.
References __heapbase, __heaptop, __malloc_init(), __malloc_sbrk(), __malloc_split(), assert, errx(), M_DATA, M_MKFIELD, M_NEXTOFF, M_OK, M_SIZE, NULL, PAGE_SIZE, and warnx().
Referenced by domalloc(), grind(), test1(), test2(), test3(), test4(), and test567().
Variable Documentation
__heapbase
uintptr_t __heapbase static
Definition at line 155 of file malloc.c.
Referenced by __malloc_init(), free(), and malloc().
__heaptop
uintptr_t __heaptop static
Definition at line 155 of file malloc.c.
Referenced by __malloc_init(), __malloc_sbrk(), __malloc_split(), __malloc_trymerge(), free(), and malloc().