var searchData=
[
  ['sb_2ec_0',['sb.c',['../d3/daf/sb_8c.html',1,'']]],
  ['sb_2eh_1',['sb.h',['../d5/d89/sb_8h.html',1,'']]],
  ['sbrktest_2ec_2',['sbrktest.c',['../db/d11/sbrktest_8c.html',1,'']]],
  ['seek_2eh_3',['seek.h',['../d3/d72/kern_2include_2kern_2seek_8h.html',1,'(Global Namespace)'],['../d7/d43/build_2install_2include_2kern_2seek_8h.html',1,'(Global Namespace)']]],
  ['semfs_2eh_4',['semfs.h',['../dd/dd8/semfs_8h.html',1,'']]],
  ['semfs_5ffsops_2ec_5',['semfs_fsops.c',['../d7/d2e/semfs__fsops_8c.html',1,'']]],
  ['semfs_5fobj_2ec_6',['semfs_obj.c',['../d1/dae/semfs__obj_8c.html',1,'']]],
  ['semfs_5fvnops_2ec_7',['semfs_vnops.c',['../dc/d9b/semfs__vnops_8c.html',1,'']]],
  ['semunit_2ec_8',['semunit.c',['../da/d61/semunit_8c.html',1,'']]],
  ['setjmp_2eh_9',['setjmp.h',['../dc/d5c/userland_2include_2setjmp_8h.html',1,'(Global Namespace)'],['../d1/dd3/build_2install_2include_2kern_2mips_2setjmp_8h.html',1,'(Global Namespace)'],['../d0/db8/build_2install_2include_2setjmp_8h.html',1,'(Global Namespace)'],['../d2/dd8/kern_2arch_2mips_2include_2kern_2setjmp_8h.html',1,'(Global Namespace)'],['../db/d7b/kern_2include_2setjmp_8h.html',1,'(Global Namespace)']]],
  ['sfs_2ec_10',['sfs.c',['../d2/d2c/sfs_8c.html',1,'']]],
  ['sfs_2eh_11',['sfs.h',['../db/dac/userland_2sbin_2sfsck_2sfs_8h.html',1,'(Global Namespace)'],['../d9/d00/kern_2include_2sfs_8h.html',1,'(Global Namespace)'],['../df/df4/kern_2include_2kern_2sfs_8h.html',1,'(Global Namespace)'],['../d4/d2f/build_2install_2include_2kern_2sfs_8h.html',1,'(Global Namespace)']]],
  ['sfs_5fballoc_2ec_12',['sfs_balloc.c',['../df/d81/sfs__balloc_8c.html',1,'']]],
  ['sfs_5fbmap_2ec_13',['sfs_bmap.c',['../df/d15/sfs__bmap_8c.html',1,'']]],
  ['sfs_5fdir_2ec_14',['sfs_dir.c',['../d7/db7/sfs__dir_8c.html',1,'']]],
  ['sfs_5ffsops_2ec_15',['sfs_fsops.c',['../dd/dd0/sfs__fsops_8c.html',1,'']]],
  ['sfs_5finode_2ec_16',['sfs_inode.c',['../de/d2f/sfs__inode_8c.html',1,'']]],
  ['sfs_5fio_2ec_17',['sfs_io.c',['../de/d7e/sfs__io_8c.html',1,'']]],
  ['sfs_5fvnops_2ec_18',['sfs_vnops.c',['../da/db1/sfs__vnops_8c.html',1,'']]],
  ['sfsprivate_2eh_19',['sfsprivate.h',['../d3/d94/sfsprivate_8h.html',1,'']]],
  ['sh_2ec_20',['sh.c',['../dd/da3/sh_8c.html',1,'']]],
  ['signal_2eh_21',['signal.h',['../d6/d34/userland_2include_2signal_8h.html',1,'(Global Namespace)'],['../d5/df9/build_2install_2include_2kern_2mips_2signal_8h.html',1,'(Global Namespace)'],['../d8/dc2/build_2install_2include_2kern_2signal_8h.html',1,'(Global Namespace)'],['../da/d79/build_2install_2include_2signal_8h.html',1,'(Global Namespace)'],['../dc/d7f/kern_2arch_2mips_2include_2kern_2signal_8h.html',1,'(Global Namespace)'],['../d6/daa/kern_2include_2kern_2signal_8h.html',1,'(Global Namespace)'],['../d7/db4/kern_2include_2signal_8h.html',1,'(Global Namespace)']]],
  ['size_5ft_2eh_22',['size_t.h',['../d4/d3d/userland_2include_2types_2size__t_8h.html',1,'(Global Namespace)'],['../d6/d27/build_2install_2include_2types_2size__t_8h.html',1,'(Global Namespace)']]],
  ['snprintf_2ec_23',['snprintf.c',['../d2/d7f/snprintf_8c.html',1,'']]],
  ['socket_2eh_24',['socket.h',['../db/d2d/build_2install_2include_2kern_2socket_8h.html',1,'(Global Namespace)'],['../d2/dcf/kern_2include_2kern_2socket_8h.html',1,'(Global Namespace)']]],
  ['sort_2ec_25',['sort.c',['../d8/d45/sort_8c.html',1,'']]],
  ['sparsefile_2ec_26',['sparsefile.c',['../d9/d9b/sparsefile_8c.html',1,'']]],
  ['specialreg_2eh_27',['specialreg.h',['../d0/d6f/specialreg_8h.html',1,'']]],
  ['spinlock_2ec_28',['spinlock.c',['../d3/d2d/spinlock_8c.html',1,'']]],
  ['spinlock_2eh_29',['spinlock.h',['../d7/d7f/include_2spinlock_8h.html',1,'(Global Namespace)'],['../d2/de8/arch_2mips_2include_2spinlock_8h.html',1,'(Global Namespace)']]],
  ['spl_2ec_30',['spl.c',['../d7/d2f/spl_8c.html',1,'']]],
  ['spl_2eh_31',['spl.h',['../d5/dba/spl_8h.html',1,'']]],
  ['stat_2eh_32',['stat.h',['../db/da1/userland_2include_2sys_2stat_8h.html',1,'(Global Namespace)'],['../df/dd2/kern_2include_2stat_8h.html',1,'(Global Namespace)'],['../d2/db4/kern_2include_2kern_2stat_8h.html',1,'(Global Namespace)'],['../df/db1/build_2install_2include_2sys_2stat_8h.html',1,'(Global Namespace)'],['../d6/d3b/build_2install_2include_2kern_2stat_8h.html',1,'(Global Namespace)']]],
  ['stattypes_2eh_33',['stattypes.h',['../d7/d84/build_2install_2include_2kern_2stattypes_8h.html',1,'(Global Namespace)'],['../d1/dcd/kern_2include_2kern_2stattypes_8h.html',1,'(Global Namespace)']]],
  ['stdarg_2eh_34',['stdarg.h',['../d4/d64/kern_2include_2stdarg_8h.html',1,'(Global Namespace)'],['../de/dc8/userland_2include_2stdarg_8h.html',1,'(Global Namespace)'],['../d1/d56/build_2install_2include_2stdarg_8h.html',1,'(Global Namespace)']]],
  ['stdbool_2eh_35',['stdbool.h',['../dd/db9/build_2install_2include_2stdbool_8h.html',1,'(Global Namespace)'],['../d3/df6/userland_2include_2stdbool_8h.html',1,'(Global Namespace)']]],
  ['stdint_2eh_36',['stdint.h',['../d2/dff/build_2install_2include_2stdint_8h.html',1,'(Global Namespace)'],['../d7/dd2/userland_2include_2stdint_8h.html',1,'(Global Namespace)']]],
  ['stdio_2eh_37',['stdio.h',['../d3/d14/build_2install_2include_2stdio_8h.html',1,'(Global Namespace)'],['../df/dd3/userland_2include_2stdio_8h.html',1,'(Global Namespace)']]],
  ['stdlib_2eh_38',['stdlib.h',['../df/d79/build_2install_2include_2stdlib_8h.html',1,'(Global Namespace)'],['../dc/dd0/userland_2include_2stdlib_8h.html',1,'(Global Namespace)']]],
  ['strcat_2ec_39',['strcat.c',['../d5/d7e/strcat_8c.html',1,'']]],
  ['strchr_2ec_40',['strchr.c',['../d6/d7b/strchr_8c.html',1,'']]],
  ['strcmp_2ec_41',['strcmp.c',['../d7/d4b/strcmp_8c.html',1,'']]],
  ['strcpy_2ec_42',['strcpy.c',['../d1/d1d/strcpy_8c.html',1,'']]],
  ['strerror_2ec_43',['strerror.c',['../d5/d04/strerror_8c.html',1,'']]],
  ['string_2eh_44',['string.h',['../d0/d55/userland_2include_2string_8h.html',1,'(Global Namespace)'],['../d2/de9/build_2install_2include_2string_8h.html',1,'(Global Namespace)']]],
  ['strlen_2ec_45',['strlen.c',['../d3/d67/strlen_8c.html',1,'']]],
  ['strrchr_2ec_46',['strrchr.c',['../dd/d9c/strrchr_8c.html',1,'']]],
  ['strtok_2ec_47',['strtok.c',['../d7/d7c/strtok_8c.html',1,'']]],
  ['strtok_5fr_2ec_48',['strtok_r.c',['../d5/db2/strtok__r_8c.html',1,'']]],
  ['subdi3_2ec_49',['subdi3.c',['../de/d69/subdi3_8c.html',1,'']]],
  ['support_2ec_50',['support.c',['../de/d12/support_8c.html',1,'']]],
  ['support_2eh_51',['support.h',['../dd/d87/support_8h.html',1,'']]],
  ['switchframe_2ec_52',['switchframe.c',['../d4/d3c/switchframe_8c.html',1,'']]],
  ['switchframe_2eh_53',['switchframe.h',['../df/dc3/switchframe_8h.html',1,'']]],
  ['sync_2ec_54',['sync.c',['../db/dc2/sync_8c.html',1,'']]],
  ['synch_2ec_55',['synch.c',['../d1/d0d/synch_8c.html',1,'']]],
  ['synch_2eh_56',['synch.h',['../db/d71/synch_8h.html',1,'']]],
  ['synchtest_2ec_57',['synchtest.c',['../d5/d86/synchtest_8c.html',1,'']]],
  ['syscall_2ec_58',['syscall.c',['../db/dd8/syscall_8c.html',1,'']]],
  ['syscall_2eh_59',['syscall.h',['../d6/dff/build_2install_2include_2kern_2syscall_8h.html',1,'(Global Namespace)'],['../d0/dd1/kern_2include_2kern_2syscall_8h.html',1,'(Global Namespace)'],['../dc/d6d/kern_2include_2syscall_8h.html',1,'(Global Namespace)']]],
  ['system_2ec_60',['system.c',['../d4/dfd/system_8c.html',1,'']]]
];
