os161-doc: /home/parallels/os161/os161-base-2.0.3/userland/sbin/sfsck/utils.h File Reference
utils.h File Reference
#include <sys/types.h>
#include <stdint.h>
Functions
void * domalloc (size_t len)
void * dorealloc (void *op, size_t osz, size_t nsz)
uint32_t uniqueid (void)
int checknullstring (char *buf, size_t maxlen)
int checkbadstring (char *buf)
int checkzeroed (void *buf, size_t len)
Function Documentation
checkbadstring()
int checkbadstring (char * buf)
Definition at line 113 of file utils.c.
References buf.
Referenced by pass1_direntry(), and sb_check().
checknullstring()
int checknullstring (char * buf, size_t maxlen)
Definition at line 96 of file utils.c.
References buf.
Referenced by pass1_direntry(), and sb_check().
checkzeroed()
int checkzeroed (void * buf, size_t len)
Definition at line 131 of file utils.c.
References buf.
Referenced by pass1_inode(), and sb_check().
domalloc()
void * domalloc (size_t len)
Definition at line 43 of file utils.c.
References errx(), EXIT_FATAL, malloc(), and NULL.
Referenced by dorealloc(), freemap_setup(), pass1_dir(), and pass2_dir().
dorealloc()
void * dorealloc (void * op, size_t osz, size_t nsz)
Definition at line 58 of file utils.c.
References domalloc(), errx(), EXIT_FATAL, free(), memcpy(), and NULL.
Referenced by inode_addtable().
uniqueid()
uint32_t uniqueid (void)
Definition at line 84 of file utils.c.
Referenced by pass1_direntry(), and pass2_dir().