os161-doc: /home/parallels/os161/os161-base-2.0.3/build/install/include/string.h File Reference
string.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Functions
char * strcat (char *, const char *)
char * strcpy (char *, const char *)
char * strchr (const char *, int)
char * strrchr (const char *, int)
int strcmp (const char *, const char *)
size_t strlen (const char *)
char * strtok_r (char *, const char *, char **)
char * strtok (char *, const char *)
void * memset (void *, int c, size_t)
void * memcpy (void *, const void *, size_t)
void * memmove (void *, const void *, size_t)
int memcmp (const void *, const void *, size_t)
const char * strerror (int errcode)
void bzero (void *, size_t)
Function Documentation
bzero()
void bzero (void * vblock, size_t len)
Definition at line 49 of file bzero.c.
Referenced by as_zero_region(), bitmap_create(), dev_stat(), emufs_stat(), enter_new_process(), fakethread_create(), lscreen_newline(), pass2_dir(), semfs_dirstat(), semfs_semstat(), sfs_bmap(), sfs_dir_link(), sfs_dir_unlink(), sfs_metaio(), sfs_partialio(), sfs_readdirblock(), sfs_stat(), switchframe_init(), writerootdir(), and writesuper().
memcmp()
int memcmp (const void * av, const void * bv, size_t len)
Definition at line 38 of file memcmp.c.
Referenced by check_slogan(), getenv(), and matches_at().
memcpy()
void * memcpy (void * dst, const void * src, size_t len)
Definition at line 48 of file memcpy.c.
Referenced by array_preallocate(), copyin(), copyout(), dorealloc(), execvp(), memmove(), prepdata(), sfs_metaio(), and sort().
memmove()
void * memmove (void * dst, const void * src, size_t len)
Definition at line 49 of file memmove.c.
References memcpy().
Referenced by array_remove(), as_copy(), lscreen_newline(), main(), pipe_unaligned(), and uiomove().
memset()
void * memset (void * ptr, int c, size_t len)
Definition at line 42 of file memset.c.
References ch.
Referenced by main(), main(), poison(), prepdata(), semV(), semV(), sfs_writedir(), test4(), traverse_ib(), Vn(), and write_badfd().
strcat()
char * strcat (char * dest, const char * src)
Definition at line 47 of file strcat.c.
References strcpy(), and strlen().
Referenced by dir_test(), do_renamexd(), main(), mkfile(), mkrawname(), and vfs_setbootfs().
strchr()
char * strchr (const char * s, int ch_arg)
Definition at line 47 of file strchr.c.
References ch, and NULL.
Referenced by __pf_send(), atoi(), execvp(), getenv(), main(), main(), strtok_r(), and vfs_setbootfs().
strcmp()
int strcmp (const char * a, const char * b)
Definition at line 48 of file strcmp.c.
Referenced by cat(), check(), check_order(), checkmany(), cmd_dispatch(), cmd_kheapdump(), cmd_mount(), createstress_thread(), dirsortfunc(), do_semu1011(), do_semu89(), docommand(), dumpargs(), findentry(), findmount(), findworkload(), fstest_read(), inspectdir(), main(), name_find(), opendisk(), pass1_dir(), pass2_dir(), readfile(), readone(), recursedir(), samestring(), semfs_creat(), semfs_lookup(), semfs_remove(), semu1(), semu1213(), semu18(), semu19(), sfs_dir_findname(), strtosize(), test6(), and vfs_getroot().
strcpy()
char * strcpy (char * dest, const char * src)
Definition at line 46 of file strcpy.c.
Referenced by cmd_progthread(), createstress_thread(), dir_test(), do_renamexd(), emu_open(), emufs_lookparent(), fill(), fstest_read(), fstest_remove(), fstest_write(), kstrdup(), main(), mkrawname(), number_init(), printfile(), semfs_lookparent(), sfs_dir_link(), sfs_lookparent(), sfsdir_tryadd(), strcat(), system(), and writesuper().
strerror()
const char * strerror (int errcode)
Definition at line 55 of file misc.c.
References NULL, panic(), sys_errlist, and sys_nerr.
Referenced by __printerr(), cleanup_rmdir(), cmd_deadlock(), cmd_progthread(), cmd_pwd(), common_prog(), cpu_create(), createstress_thread(), cvtest(), dev_create_vnode(), devnull_create(), docreatestress(), dofork(), dolongstress(), domkdir(), doreadstress(), dorename(), dormdir(), dowritestress(), dowritestress2(), fstest_read(), fstest_remove(), fstest_write(), kmallocstress(), kmalloctest4(), locktest(), make_computes(), make_sleepalots(), menu_execute(), printfile(), recursive_cleanup(), report_result(), report_warn(), run(), runthreads(), semfs_bootstrap(), semfs_getroot(), semtest(), setup(), setup(), sfs_rename(), tryattach_beep_to_ltimer(), tryattach_con_to_lser(), tryattach_emu_to_lamebus(), tryattach_lhd_to_lamebus(), tryattach_lrandom_to_lamebus(), tryattach_lser_to_lamebus(), tryattach_ltimer_to_lamebus(), tryattach_ltrace_to_lamebus(), tryattach_random_to_lrandom(), tryattach_rtclock_to_ltimer(), vfs_unmountall(), vnode_decref(), and vscomplain().
strlen()
size_t strlen (const char * str)
Definition at line 47 of file strlen.c.
Referenced by __bad_assert(), __pf_printstuff(), __puts(), __senderrstr(), check_slogan(), checkfilesystem(), chkfile(), cmd_bootfs(), cmd_mount(), cmd_progthread(), cmd_unmount(), complain(), complainx(), createstress_thread(), dev_lookup(), dir_test(), dotest(), dumpargs(), dumpval(), emu_open(), emufs_lookparent(), execvp(), fill(), fstest_makename(), fstest_read(), fstest_write(), getenv(), getnum(), kstrdup(), lseek_file_stdin(), lseek_loc_pasteof(), main(), main(), main(), mkfile(), mkfile(), mkrawname(), number_init(), open_testfile(), opendisk(), pass1_dir(), pass2_dir(), prepdata(), say(), say(), say(), semfs_getdirentry(), semfs_lookparent(), sfs_dir_link(), sfs_lookparent(), sfsdir_tryadd(), strcat(), strrchr(), system(), vfs_getcwd(), vfs_lookparent(), vfs_lookup(), vfs_setbootfs(), vfs_swapon(), vsay(), vscomplain(), write_slogan(), and writesuper().
strrchr()
char * strrchr (const char * s, int ch_arg)
Definition at line 47 of file strrchr.c.
References ch, NULL, and strlen().
Referenced by basename(), emufs_lookparent(), and initprogname().
strtok()
char * strtok (char * str, const char * seps)
Definition at line 35 of file strtok.c.
References __strtok_context, seps, and strtok_r().
Referenced by docommand(), and system().
strtok_r()
char * strtok_r (char * string, const char * seps, char ** context)
Definition at line 50 of file strtok_r.c.
References NULL, seps, strchr(), and tail().
Referenced by cmd_dispatch(), menu_execute(), and strtok().