os161-doc: /home/parallels/os161/os161-base-2.0.3/build/install/include/stdlib.h File Reference
stdlib.h File Reference
#include <kern/types.h>
#include <types/size_t.h>
#include <sys/null.h>
Macros
#define RAND_MAX 0x7fffffff
Functions
int atoi (const char *)
void abort (void)
void exit (int code)
char * getenv (const char *var)
int system (const char *command)
long random (void)
void srandom (unsigned long seed)
char * initstate (unsigned long, char *, size_t)
char * setstate (char *)
void * malloc (size_t size)
void free (void *ptr)
void qsort (void *data, unsigned num, size_t size, int(*f)(const void *, const void *))
Macro Definition Documentation
RAND_MAX
#define RAND_MAX 0x7fffffff
Definition at line 67 of file stdlib.h.
Function Documentation
abort()
void abort (void)
Definition at line 42 of file abort.c.
References _exit().
Referenced by __bad_assert().
atoi()
int atoi (const char * s)
Definition at line 50 of file atoi.c.
References NULL, and strchr().
Referenced by cmd_exit(), cmd_wait(), doargs(), getnum(), kmalloctest3(), main(), main(), and threadtest3().
exit()
void exit (int code)
Definition at line 38 of file exit.c.
References _exit().
Referenced by assemble(), checksize_bins(), checksize_merge(), checksize_valid(), cmd_exit(), doargs(), doclose(), doexactread(), dofork(), doforkall(), dohardlink(), dolseek(), doopen(), doread(), dovalidate(), dowait(), dowait(), dowrite(), exec_badargs(), exec_badprog(), exec_emptyprog(), exec_onearg(), genkeys(), test::getargs(), getsize(), go(), main(), main(), makeprocs(), mergebins(), runit(), runtaskgroup(), setup(), sort(), sortbins(), stresstest(), test10(), test11(), test12(), test13(), test14(), test15(), test3(), test4(), test9(), try___getcwd(), try___time(), try_chdir(), try_close(), try_dup2(), try_execv(), try_fstat(), try_fsync(), try_ftruncate(), try_getdirentry(), try_ioctl(), try_link(), try_lseek(), try_lstat(), try_mkdir(), try_open(), try_pipe(), try_read(), try_readlink(), try_remove(), try_rename(), try_rmdir(), try_stat(), try_symlink(), try_waitpid(), try_write(), usage(), usage(), usage(), usage(), validate(), verr(), verrx(), wait_badflags(), wait_badstatus(), wait_nullstatus(), and wait_unaligned().
free()
void free (void * ptr)
Definition at line 534 of file malloc.c.
References __heapbase, __heaptop, __malloc_deadbeef(), __malloc_trymerge(), errx(), M_DATA, M_NEXT, M_OK, M_PREV, M_SIZE, NULL, and warnx().
Referenced by dorealloc(), pass1_dir(), pass2_dir(), test1(), test2(), test3(), test4(), and test567().
getenv()
char * getenv (const char * var)
Definition at line 56 of file getenv.c.
References __default_environ, __environ, memcmp(), NULL, strchr(), and strlen().
Referenced by execvp().
initstate()
char * initstate (unsigned long seed, char * arg_state, size_t n)
Definition at line 282 of file random.c.
References assert, BREAK_0, BREAK_1, BREAK_2, BREAK_3, BREAK_4, DEG_0, DEG_1, DEG_2, DEG_3, DEG_4, end_ptr, LOCKME, MAX_TYPES, NULL, rand_deg, rand_sep, rand_type, rptr, SEP_0, SEP_1, SEP_2, SEP_3, SEP_4, srandom_unlocked(), state, TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
malloc()
void * malloc (size_t size)
Definition at line 352 of file malloc.c.
References __heapbase, __heaptop, __malloc_init(), __malloc_sbrk(), __malloc_split(), assert, errx(), M_DATA, M_MKFIELD, M_NEXTOFF, M_OK, M_SIZE, NULL, PAGE_SIZE, and warnx().
Referenced by domalloc(), grind(), test1(), test2(), test3(), test4(), and test567().
qsort()
void qsort (void * data, unsigned num, size_t size, int(*)(const void *, const void *) f)
Definition at line 38 of file qsort.c.
References assert, COMPARE, EXCHANGE, f, num, qsort(), and tail().
Referenced by grind(), inode_sorttable(), and sfsdir_sort().
random()
long random (void)
Definition at line 143 of file random.c.
References NULL, panic(), random_softc::rs_devdata, random_softc::rs_random, and the_random.
Referenced by bitmaptest(), choose_name(), compute_thread(), file_randomwrite(), fill(), genkeys(), genkeys_sub(), grind(), init(), initarray(), mkrandtree_sub(), pickpage(), randchar(), randop(), randsize(), randtruncate(), randwrite(), readallrandomly(), rmrandtree_sub(), sleepalot_thread(), stresstest(), test567(), testa(), waker_thread(), wl_diropseq(), wl_genseq(), wl_linkunlinkseq(), wl_mkrandtree(), wl_mkrmseq(), wl_renameseq(), wl_rmrandtree(), wl_writefileseq(), and wl_writetruncseq().
setstate()
char * setstate (char * arg_state)
Definition at line 354 of file random.c.
References assert, degrees, end_ptr, fptr, LOCKME, MAX_TYPES, NULL, rand_deg, rand_sep, rand_type, rptr, seps, state, TYPE_0, TYPE_1, TYPE_2, TYPE_3, TYPE_4, and UNLOCKME.
srandom()
void srandom (unsigned long seed)
Definition at line 250 of file random.c.
References LOCKME, srandom_unlocked(), and UNLOCKME.
Referenced by genkeys(), genkeys_sub(), grind(), init(), initarray(), main(), prepwords(), readallrandomly(), stresstest(), test567(), wl_diropseq(), wl_fillhole(), wl_genseq(), wl_linkunlinkseq(), wl_mkrandtree(), wl_mkrmseq(), wl_randupdate(), wl_renameseq(), wl_rmrandtree(), wl_truncfill(), wl_writefileseq(), and wl_writetruncseq().
system()
int system (const char * command)
Definition at line 45 of file system.c.
References _exit(), E2BIG, errno, execv(), fork(), MAXARGS, MAXCMDSIZE, NULL, pid, strcpy(), strlen(), strtok(), and waitpid().