os161-doc: /home/parallels/os161/os161-base-2.0.3/kern/test/threadlisttest.c File Reference
threadlisttest.c File Reference
#include <types.h>
#include <lib.h>
#include <thread.h>
#include <threadlist.h>
#include <test.h>
Macros
#define NUMNAMES 7
#define FAKE_MAGIC ((void *)0xbaabaa)
Functions
static struct thread * fakethread_create (const char *name)
static void fakethread_destroy (struct thread *t)
static void check_order (struct threadlist *tl, bool rev)
static void threadlisttest_a (void)
static void threadlisttest_b (void)
static void threadlisttest_c (void)
static void threadlisttest_d (void)
static void threadlisttest_e (void)
static void threadlisttest_f (void)
int threadlisttest (int nargs, char **args)
Variables
static const char *const names [NUMNAMES]
static struct thread * fakethreads [NUMNAMES]
Macro Definition Documentation
FAKE_MAGIC
#define FAKE_MAGIC ((void *)0xbaabaa)
Definition at line 52 of file threadlisttest.c.
NUMNAMES
#define NUMNAMES 7
Definition at line 36 of file threadlisttest.c.
Function Documentation
check_order()
static void check_order (struct threadlist * tl, bool rev) static
Definition at line 96 of file threadlisttest.c.
References KASSERT, strcmp(), thread::t_name, and THREADLIST_FORALL.
Referenced by threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), and threadlisttest_e().
fakethread_create()
static struct thread * fakethread_create (const char * name) static
Definition at line 59 of file threadlisttest.c.
References bzero(), FAKE_MAGIC, kmalloc(), kstrdup(), name, NULL, panic(), thread::t_listnode, thread::t_name, thread::t_stack, and threadlistnode_init().
Referenced by threadlisttest().
fakethread_destroy()
static void fakethread_destroy (struct thread * t) static
Definition at line 83 of file threadlisttest.c.
References FAKE_MAGIC, KASSERT, kfree(), thread::t_listnode, thread::t_name, thread::t_stack, and threadlistnode_cleanup().
Referenced by threadlisttest().
threadlisttest()
int threadlisttest (int nargs, char ** args)
Definition at line 316 of file threadlisttest.c.
References fakethread_create(), fakethread_destroy(), fakethreads, kprintf(), names, NULL, NUMNAMES, threadlisttest_a(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), threadlisttest_e(), and threadlisttest_f().
threadlisttest_a()
static void threadlisttest_a (void) static
Definition at line 122 of file threadlisttest.c.
References KASSERT, threadlist_cleanup(), threadlist_init(), and threadlist_isempty().
Referenced by threadlisttest().
threadlisttest_b()
static void threadlisttest_b (void) static
Definition at line 133 of file threadlisttest.c.
References check_order(), fakethreads, KASSERT, threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_remhead(), threadlist_remtail(), and threadlist::tl_count.
Referenced by threadlisttest().
threadlisttest_c()
static void threadlisttest_c (void) static
Definition at line 161 of file threadlisttest.c.
References check_order(), fakethreads, KASSERT, threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_remhead(), threadlist_remtail(), and threadlist::tl_count.
Referenced by threadlisttest().
threadlisttest_d()
static void threadlisttest_d (void) static
Definition at line 197 of file threadlisttest.c.
References check_order(), fakethreads, KASSERT, threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_remhead(), threadlist_remtail(), and threadlist::tl_count.
Referenced by threadlisttest().
threadlisttest_e()
static void threadlisttest_e (void) static
Definition at line 233 of file threadlisttest.c.
References check_order(), fakethreads, KASSERT, thread::t_listnode, threadlist_addhead(), threadlist_addtail(), threadlist_cleanup(), threadlist_init(), threadlist_insertafter(), threadlist_insertbefore(), threadlist_remhead(), threadlist::tl_count, threadlistnode::tln_prev, and threadlistnode::tln_self.
Referenced by threadlisttest().
threadlisttest_f()
static void threadlisttest_f (void) static
Definition at line 278 of file threadlisttest.c.
References fakethreads, KASSERT, NUMNAMES, threadlist_addtail(), THREADLIST_FORALL, THREADLIST_FORALL_REV, threadlist_init(), threadlist_remhead(), and threadlist::tl_count.
Referenced by threadlisttest().
Variable Documentation
fakethreads
struct thread* fakethreads[NUMNAMES] static
Definition at line 47 of file threadlisttest.c.
Referenced by threadlisttest(), threadlisttest_b(), threadlisttest_c(), threadlisttest_d(), threadlisttest_e(), and threadlisttest_f().
names
const char* const names[NUMNAMES] static
Initial value:
= {
    "Aillard",
    "Aldaran",
    "Alton",
    "Ardais",
    "Elhalyn",
    "Hastur",
    "Ridenow",
}
Definition at line 37 of file threadlisttest.c.
Referenced by fill(), and threadlisttest().