os161-doc: /home/parallels/os161/os161-base-2.0.3/userland/testbin/frack/check.c File Reference
check.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <unistd.h>
#include <limits.h>
#include <assert.h>
#include <errno.h>
#include <err.h>
#include "name.h"
#include "data.h"
#include "pool.h"
#include "check.h"
Data Structures
struct fschange
struct fsdirent
struct fsobject
Macros
#define UNKNOWN_ID ((unsigned)-1)
#define MAXCHANGES 16384
#define MAXOBJECTS 16384
#define MAXDIRENTS 16384
Enumerations
enum fschanges {
FC_NEWFS , FC_TRUNCATE , FC_WRITE , FC_CREAT ,
FC_MKDIR , FC_RMDIR , FC_UNLINK , FC_LINK ,
FC_RENAMEFILE , FC_RENAMEDIR
}
Functions
DECLPOOL (fschange, MAXCHANGES)
DECLPOOL (fsobject, MAXOBJECTS)
DECLPOOL (fsdirent, MAXDIRENTS)
static struct fschange * getchange (void)
static struct fsobject * getobject (void)
static struct fsdirent * getdirent (void)
static void putobject (struct fsobject *obj)
static void putdirent (struct fsdirent *dirent)
static struct fschange * fc_create (enum fschanges type)
static struct fschange * fc_create_newfs (unsigned rootdirnum)
static struct fschange * fc_create_truncate (struct fschange *prev_thisfile, unsigned file, off_t len)
static struct fschange * fc_create_write (struct fschange *prev_thisfile, unsigned file, off_t pos, off_t len, off_t oldfilesize, unsigned code, unsigned seq)
static struct fschange * fc_create_creat (struct fschange *prev_thisdir, unsigned dir, unsigned name, unsigned newfile)
static struct fschange * fc_create_mkdir (struct fschange *prev_thisdir, unsigned dir, unsigned name, unsigned newdir)
static struct fschange * fc_create_rmdir (struct fschange *prev_thisdir, struct fschange *prev_victimdir, unsigned dir, unsigned name, unsigned victimdir)
static struct fschange * fc_create_unlink (struct fschange *prev_thisdir, struct fschange *prev_victimfile, unsigned dir, unsigned name, unsigned victimfile)
static struct fschange * fc_create_link (struct fschange *prev_fromdir, struct fschange *prev_todir, struct fschange *prev_thisfile, unsigned fromdir, unsigned fromname, unsigned todir, unsigned toname, unsigned file)
static struct fschange * fc_create_renamefile (struct fschange *prev_fromdir, struct fschange *prev_todir, struct fschange *prev_movedfile, unsigned fromdir, unsigned fromname, unsigned todir, unsigned toname, unsigned movedfile)
static struct fschange * fc_create_renamedir (struct fschange *prev_fromdir, struct fschange *prev_todir, struct fschange *prev_moveddir, unsigned fromdir, unsigned fromname, unsigned todir, unsigned toname, unsigned moveddir)
static struct fsdirent * fsdirent_create (unsigned name, struct fsobject *obj)
static void fsdirent_destroy (struct fsdirent *de)
static struct fsobject * fsobject_create_file (unsigned id)
static struct fsobject * fsobject_create_dir (unsigned id, struct fsobject *parent)
static void fsobject_incref (struct fsobject *obj)
static void fsobject_decref (struct fsobject *obj)
static void fsobject_destroytree (struct fsobject *obj)
static void die (const char *fmt,...)
static void fsdir_add_entry (struct fsobject *dir, struct fsdirent *nde)
static struct fsdirent * fsdir_find_entry (struct fsobject *dir, unsigned name, int croak)
static struct fsdirent * fsdir_remove_entry (struct fsobject *dir, unsigned name)
static struct fsobject * findsub (struct fsobject *obj, unsigned isdir, unsigned id)
static struct fsobject * findfile_maybe (struct fsobject *rootdir, unsigned id)
static struct fsobject * finddir (struct fsobject *rootdir, unsigned id)
static void apply_change (struct fsobject *rootdir, struct fschange *change)
static void fc_attach (struct fschange *new)
static void rewindstate (void)
static void advancestateto (struct fschange *targetchange)
static struct fschange * changes_findprevfile (unsigned filenum)
static struct fschange * changes_findprevdir (unsigned dirnum)
static unsigned model_findfile (unsigned dirnum, unsigned name)
static unsigned model_finddir (unsigned dirnum, unsigned name)
static unsigned model_findparent (unsigned dirnum)
static unsigned model_isfile (unsigned dirnum, unsigned name)
static unsigned model_isdir (unsigned dirnum, unsigned name)
static off_t model_getfilesize (unsigned filenum)
void check_setup (void)
int check_createfile (unsigned name)
int check_openfile (unsigned name)
void check_closefile (int handle, unsigned name)
void check_write (int handle, unsigned name, unsigned code, unsigned seq, off_t pos, off_t len)
void check_truncate (int handle, unsigned name, off_t len)
void check_mkdir (unsigned name)
void check_rmdir (unsigned name)
void check_unlink (unsigned name)
void check_link (unsigned fromname, unsigned toname)
static void common_rename (unsigned fromdirnum, unsigned fromname, unsigned todirnum, unsigned toname)
void check_rename (unsigned from, unsigned to)
void check_renamexd (unsigned fromdir, unsigned from, unsigned todir, unsigned to)
void check_chdir (unsigned name)
void check_chdirup (void)
void check_sync (void)
static int xstat (const char *path, struct stat *buf)
static struct fsobject * inspectdir (struct fsobject *parentobj, ino_t parentino, const char *dirnamestr)
static void inspectfs (void)
static unsigned count_subtree (struct fsobject *obj)
static unsigned compare_objects (struct fsobject *obja, struct fsobject *objb)
static void doindent (unsigned depth)
static void printdiffs (unsigned indent, struct fsobject *obja, struct fsobject *objb)
static unsigned findokversion (struct fschange *change)
static struct fschange * backup_for_file (struct fschange *change, unsigned filenum)
static void checkfilezeros (int fd, const char *namestr, off_t start, off_t end)
static void readfiledata (int fd, const char *namestr, off_t regionstart, off_t checkstart, off_t checkend, off_t regionend)
static void checkfiledata (int fd, const char *namestr, unsigned code, unsigned seq, off_t zerostart, off_t regionstart, off_t checkstart, off_t checkend, off_t regionend)
static void checkfilerange (int fd, const char *namestr, struct fschange *change, off_t start, off_t end)
static int change_is_present (int fd, const char *namestr, off_t filesize, struct fschange *change)
static void checkonefilecontents (const char *namestr, struct fsobject *file, struct fschange *change)
static void checkallfilecontents (struct fsobject *dir, struct fschange *change)
void checkfs (void)
Variables
static struct fschange * firstchange
static struct fschange * changes
static struct fsobject * state
static unsigned nextfilenum
static unsigned nextdirnum
static unsigned cwd
static struct fsobject * found
static unsigned found_subdirs
static unsigned found_files
Macro Definition Documentation
MAXCHANGES
#define MAXCHANGES 16384
Definition at line 231 of file check.c.
MAXDIRENTS
#define MAXDIRENTS 16384
Definition at line 233 of file check.c.
MAXOBJECTS
#define MAXOBJECTS 16384
Definition at line 232 of file check.c.
UNKNOWN_ID
#define UNKNOWN_ID ((unsigned)-1)
Definition at line 59 of file check.c.
Enumeration Type Documentation
fschanges
enum fschanges
Enumerator
FC_NEWFS
FC_TRUNCATE
FC_WRITE
FC_CREAT
FC_MKDIR
FC_RMDIR
FC_UNLINK
FC_LINK
FC_RENAMEFILE
FC_RENAMEDIR
Definition at line 66 of file check.c.
Function Documentation
advancestateto()
static void advancestateto (struct fschange * targetchange) static
Definition at line 982 of file check.c.
References apply_change(), assert, firstchange, fschange::next, NULL, and state.
Referenced by checkfs().
apply_change()
static void apply_change (struct fsobject * rootdir, struct fschange * change) static
Definition at line 743 of file check.c.
References assert, fschange::dir, fsobject::entries, FC_CREAT, fschange::fc_creat, FC_LINK, fschange::fc_link, FC_MKDIR, fschange::fc_mkdir, FC_NEWFS, fschange::fc_newfs, FC_RENAMEDIR, fschange::fc_renamedir, FC_RENAMEFILE, fschange::fc_renamefile, FC_RMDIR, fschange::fc_rmdir, FC_TRUNCATE, fschange::fc_truncate, FC_UNLINK, fschange::fc_unlink, FC_WRITE, fschange::fc_write, fschange::file, finddir(), findfile_maybe(), fschange::fromdir, fschange::fromname, fsdir_add_entry(), fsdir_find_entry(), fsdir_remove_entry(), fsdirent_create(), fsdirent_destroy(), fsobject_create_dir(), fsobject_create_file(), fsobject_decref(), fsobject_incref(), fsobject::identity, fsobject::isdir, fschange::len, fsobject::len, fschange::moveddir, fschange::movedfile, fschange::name, fsdirent::name, fschange::newdir, fschange::newfile, NULL, fsdirent::obj, fsobject::obj_dir, fsobject::obj_file, fsobject::parent, fschange::pos, fsobject::refcount, fschange::rootdirnum, fschange::todir, fschange::toname, fschange::type, fschange::victimdir, and fschange::victimfile.
Referenced by advancestateto(), check_setup(), checkfs(), and fc_attach().
backup_for_file()
static struct fschange * backup_for_file (struct fschange * change, unsigned filenum) static
Definition at line 2288 of file check.c.
References FC_CREAT, fschange::fc_creat, FC_TRUNCATE, fschange::fc_truncate, FC_WRITE, fschange::fc_write, fschange::file, fschange::newfile, NULL, fschange::prev, and fschange::type.
Referenced by checkonefilecontents().
change_is_present()
static int change_is_present (int fd, const char * namestr, off_t filesize, struct fschange * change) static
Definition at line 2594 of file check.c.
References assert, fschange::code, data_matches(), FC_CREAT, FC_TRUNCATE, fschange::fc_truncate, FC_WRITE, fschange::fc_write, fd, fschange::len, fschange::oldfilesize, pos, fschange::pos, readfiledata(), fschange::seq, and fschange::type.
Referenced by checkonefilecontents().
changes_findprevdir()
static struct fschange * changes_findprevdir (unsigned dirnum) static
Definition at line 1068 of file check.c.
References changes, die(), fschange::dir, FC_CREAT, fschange::fc_creat, FC_LINK, fschange::fc_link, FC_MKDIR, fschange::fc_mkdir, FC_NEWFS, fschange::fc_newfs, FC_RENAMEDIR, fschange::fc_renamedir, FC_RENAMEFILE, fschange::fc_renamefile, FC_RMDIR, fschange::fc_rmdir, FC_TRUNCATE, FC_UNLINK, fschange::fc_unlink, FC_WRITE, fschange::fromdir, fschange::moveddir, fschange::newdir, NULL, fschange::prev, fschange::rootdirnum, fschange::todir, fschange::type, and fschange::victimdir.
Referenced by check_createfile(), check_link(), check_mkdir(), check_rmdir(), check_unlink(), and common_rename().
changes_findprevfile()
static struct fschange * changes_findprevfile (unsigned filenum) static
Definition at line 1012 of file check.c.
References changes, die(), FC_CREAT, fschange::fc_creat, FC_LINK, fschange::fc_link, FC_MKDIR, FC_NEWFS, FC_RENAMEDIR, FC_RENAMEFILE, fschange::fc_renamefile, FC_RMDIR, FC_TRUNCATE, fschange::fc_truncate, FC_UNLINK, fschange::fc_unlink, FC_WRITE, fschange::fc_write, fschange::file, fschange::movedfile, fschange::newfile, NULL, fschange::prev, fschange::type, and fschange::victimfile.
Referenced by check_link(), check_truncate(), check_unlink(), check_write(), and common_rename().
check_chdir()
void check_chdir (unsigned name)
Definition at line 1833 of file check.c.
References cwd, model_finddir(), and name.
Referenced by op_chdir().
check_chdirup()
void check_chdirup (void)
Definition at line 1842 of file check.c.
References cwd, and model_findparent().
Referenced by op_chdirup().
check_closefile()
void check_closefile (int handle, unsigned name)
Definition at line 1635 of file check.c.
References name.
Referenced by op_close().
check_createfile()
int check_createfile (unsigned name)
Definition at line 1610 of file check.c.
References changes_findprevdir(), cwd, fc_attach(), fc_create_creat(), name, and nextfilenum.
Referenced by op_open().
check_link()
void check_link (unsigned fromname, unsigned toname)
Definition at line 1733 of file check.c.
References changes_findprevdir(), changes_findprevfile(), cwd, fc_attach(), fc_create_link(), fschange::fromname, model_findfile(), and fschange::toname.
Referenced by op_link().
check_mkdir()
void check_mkdir (unsigned name)
Definition at line 1687 of file check.c.
References changes_findprevdir(), cwd, fc_attach(), fc_create_mkdir(), name, and nextdirnum.
Referenced by op_mkdir().
check_openfile()
int check_openfile (unsigned name)
Definition at line 1626 of file check.c.
References cwd, model_findfile(), and name.
Referenced by op_open().
check_rename()
void check_rename (unsigned from, unsigned to)
Definition at line 1809 of file check.c.
References common_rename(), and cwd.
Referenced by op_rename().
check_renamexd()
void check_renamexd (unsigned fromdir, unsigned from, unsigned todir, unsigned to)
Definition at line 1818 of file check.c.
References common_rename(), cwd, fschange::fromdir, model_finddir(), and fschange::todir.
Referenced by op_renamexd().
check_rmdir()
void check_rmdir (unsigned name)
Definition at line 1701 of file check.c.
References changes_findprevdir(), cwd, fc_attach(), fc_create_rmdir(), model_finddir(), and name.
Referenced by op_rmdir().
check_setup()
void check_setup (void)
Definition at line 1585 of file check.c.
References apply_change(), assert, changes, cwd, fc_create_newfs(), firstchange, nextdirnum, nextfilenum, NULL, rewindstate(), and state.
Referenced by setcheckmode().
check_sync()
void check_sync (void)
Definition at line 1851 of file check.c.
Referenced by op_sync().
check_truncate()
void check_truncate (int handle, unsigned name, off_t len)
Definition at line 1670 of file check.c.
References assert, changes_findprevfile(), fc_attach(), fc_create_truncate(), fschange::len, name, and nextfilenum.
Referenced by op_truncate().
check_unlink()
void check_unlink (unsigned name)
Definition at line 1717 of file check.c.
References changes_findprevdir(), changes_findprevfile(), cwd, fc_attach(), fc_create_unlink(), model_findfile(), and name.
Referenced by op_unlink().
check_write()
void check_write (int handle, unsigned name, unsigned code, unsigned seq, off_t pos, off_t len)
Definition at line 1648 of file check.c.
References assert, changes_findprevfile(), fschange::code, fc_attach(), fc_create_write(), fschange::len, model_getfilesize(), name, nextfilenum, pos, and fschange::seq.
Referenced by op_write().
checkallfilecontents()
static void checkallfilecontents (struct fsobject * dir, struct fschange * change) static
Definition at line 2775 of file check.c.
References assert, chdir(), checkallfilecontents(), checkonefilecontents(), err(), fsobject::isdir, fsdirent::name, name_get(), fsdirent::next, NULL, fsdirent::obj, and printf().
Referenced by checkallfilecontents(), and checkfs().
checkfiledata()
static void checkfiledata (int fd, const char * namestr, unsigned code, unsigned seq, off_t zerostart, off_t regionstart, off_t checkstart, off_t checkend, off_t regionend) static
Definition at line 2431 of file check.c.
References fschange::code, data_check(), fd, printf(), readfiledata(), and fschange::seq.
Referenced by checkfilerange().
checkfilerange()
static void checkfilerange (int fd, const char * namestr, struct fschange * change, off_t start, off_t end) static
Definition at line 2459 of file check.c.
References assert, checkfiledata(), checkfilerange(), checkfilezeros(), fschange::code, FC_CREAT, FC_RENAMEFILE, fschange::fc_renamefile, FC_TRUNCATE, fschange::fc_truncate, FC_WRITE, fschange::fc_write, fd, fschange::len, fschange::oldfilesize, fschange::pos, fschange::prev, fschange::prev_movedfile, fschange::prev_thisfile, fschange::seq, and fschange::type.
Referenced by checkfilerange(), and checkonefilecontents().
checkfilezeros()
static void checkfilezeros (int fd, const char * namestr, off_t start, off_t end) static
Definition at line 2321 of file check.c.
References buf, err(), errx(), fd, fschange::len, lseek(), poison(), POISON_VAL, printf(), read(), and SEEK_SET.
Referenced by checkfilerange().
checkfs()
void checkfs (void)
Definition at line 2808 of file check.c.
References advancestateto(), apply_change(), assert, changes, checkallfilecontents(), compare_objects(), FC_NEWFS, firstchange, found, found_files, found_subdirs, inspectfs(), fschange::next, nextdirnum, nextfilenum, NULL, fschange::partial, printdiffs(), printf(), rewindstate(), state, fschange::type, and fschange::version.
Referenced by complete().
checkonefilecontents()
static void checkonefilecontents (const char * namestr, struct fsobject * file, struct fschange * change) static
Definition at line 2636 of file check.c.
References assert, backup_for_file(), change_is_present(), checkfilerange(), close(), die(), err(), FC_CREAT, FC_TRUNCATE, fschange::fc_truncate, FC_WRITE, fschange::fc_write, fd, findokversion(), fschange::len, NULL, O_RDONLY, open(), fschange::pos, fschange::prev, printf(), fschange::type, and fschange::version.
Referenced by checkallfilecontents().
common_rename()
static void common_rename (unsigned fromdirnum, unsigned fromname, unsigned todirnum, unsigned toname) static
Definition at line 1751 of file check.c.
References assert, changes_findprevdir(), changes_findprevfile(), fc_attach(), fc_create_renamedir(), fc_create_renamefile(), fc_create_rmdir(), fc_create_unlink(), fschange::fromname, model_finddir(), model_findfile(), model_isdir(), model_isfile(), NULL, fschange::partial, and fschange::toname.
Referenced by check_rename(), and check_renamexd().
compare_objects()
static unsigned compare_objects (struct fsobject * obja, struct fsobject * objb) static
Definition at line 2053 of file check.c.
References assert, compare_objects(), count_subtree(), fsobject::entries, found, fsobject::isdir, fsobject::len, fsdirent::name, fsdirent::next, NULL, fsdirent::obj, fsobject::obj_dir, and fsobject::obj_file.
Referenced by checkfs(), and compare_objects().
count_subtree()
static unsigned count_subtree (struct fsobject * obj) static
Definition at line 2034 of file check.c.
References count_subtree(), fsobject::entries, fsobject::isdir, fsdirent::next, NULL, fsdirent::obj, and fsobject::obj_dir.
Referenced by compare_objects(), count_subtree(), and printdiffs().
DECLPOOL() [1/3]
DECLPOOL (fschange , MAXCHANGES)
DECLPOOL() [2/3]
DECLPOOL (fsdirent , MAXDIRENTS)
DECLPOOL() [3/3]
DECLPOOL (fsobject , MAXOBJECTS)
die()
static void die (const char * fmt, ...) static
Definition at line 580 of file check.c.
References buf, errx(), va_end, va_start, and vsnprintf().
Referenced by changes_findprevdir(), changes_findprevfile(), checkonefilecontents(), finddir(), fsdir_add_entry(), fsdir_find_entry(), fsdir_remove_entry(), model_finddir(), and model_findfile().
doindent()
static void doindent (unsigned depth) static
Definition at line 2146 of file check.c.
References printf().
Referenced by printdiffs().
fc_attach()
static void fc_attach (struct fschange * new) static
Definition at line 940 of file check.c.
References apply_change(), assert, changes, fschange::next, NULL, fschange::prev, state, and fschange::version.
Referenced by check_createfile(), check_link(), check_mkdir(), check_rmdir(), check_truncate(), check_unlink(), check_write(), and common_rename().
fc_create()
static struct fschange * fc_create (enum fschanges type) static
Definition at line 288 of file check.c.
References getchange(), fschange::next, NULL, fschange::partial, fschange::prev, fschange::type, and fschange::version.
Referenced by fc_create_creat(), fc_create_link(), fc_create_mkdir(), fc_create_newfs(), fc_create_renamedir(), fc_create_renamefile(), fc_create_rmdir(), fc_create_truncate(), fc_create_unlink(), and fc_create_write().
fc_create_creat()
static struct fschange * fc_create_creat (struct fschange * prev_thisdir, unsigned dir, unsigned name, unsigned newfile) static
Definition at line 345 of file check.c.
References fschange::dir, FC_CREAT, fschange::fc_creat, fc_create(), name, fschange::name, fschange::newfile, and fschange::prev_thisdir.
Referenced by check_createfile().
fc_create_link()
static struct fschange * fc_create_link (struct fschange * prev_fromdir, struct fschange * prev_todir, struct fschange * prev_thisfile, unsigned fromdir, unsigned fromname, unsigned todir, unsigned toname, unsigned file) static
Definition at line 408 of file check.c.
References fc_create(), FC_LINK, fschange::fc_link, fschange::file, fschange::fromdir, fschange::fromname, fschange::prev_fromdir, fschange::prev_thisfile, fschange::prev_todir, fschange::todir, and fschange::toname.
Referenced by check_link().
fc_create_mkdir()
static struct fschange * fc_create_mkdir (struct fschange * prev_thisdir, unsigned dir, unsigned name, unsigned newdir) static
Definition at line 360 of file check.c.
References fschange::dir, fc_create(), FC_MKDIR, fschange::fc_mkdir, name, fschange::name, fschange::newdir, and fschange::prev_thisdir.
Referenced by check_mkdir().
fc_create_newfs()
static struct fschange * fc_create_newfs (unsigned rootdirnum) static
Definition at line 302 of file check.c.
References fc_create(), FC_NEWFS, fschange::fc_newfs, and fschange::rootdirnum.
Referenced by check_setup().
fc_create_renamedir()
static struct fschange * fc_create_renamedir (struct fschange * prev_fromdir, struct fschange * prev_todir, struct fschange * prev_moveddir, unsigned fromdir, unsigned fromname, unsigned todir, unsigned toname, unsigned moveddir) static
Definition at line 453 of file check.c.
References fc_create(), FC_RENAMEDIR, fschange::fc_renamedir, fschange::fromdir, fschange::fromname, fschange::moveddir, fschange::prev_fromdir, fschange::prev_moveddir, fschange::prev_todir, fschange::todir, and fschange::toname.
Referenced by common_rename().
fc_create_renamefile()
static struct fschange * fc_create_renamefile (struct fschange * prev_fromdir, struct fschange * prev_todir, struct fschange * prev_movedfile, unsigned fromdir, unsigned fromname, unsigned todir, unsigned toname, unsigned movedfile) static
Definition at line 430 of file check.c.
References fc_create(), FC_RENAMEFILE, fschange::fc_renamefile, fschange::fromdir, fschange::fromname, fschange::movedfile, fschange::prev_fromdir, fschange::prev_movedfile, fschange::prev_todir, fschange::todir, and fschange::toname.
Referenced by common_rename().
fc_create_rmdir()
static struct fschange * fc_create_rmdir (struct fschange * prev_thisdir, struct fschange * prev_victimdir, unsigned dir, unsigned name, unsigned victimdir) static
Definition at line 375 of file check.c.
References fschange::dir, fc_create(), FC_RMDIR, fschange::fc_rmdir, name, fschange::name, fschange::prev_thisdir, fschange::prev_victimdir, and fschange::victimdir.
Referenced by check_rmdir(), and common_rename().
fc_create_truncate()
static struct fschange * fc_create_truncate (struct fschange * prev_thisfile, unsigned file, off_t len) static
Definition at line 313 of file check.c.
References fc_create(), FC_TRUNCATE, fschange::fc_truncate, fschange::file, fschange::len, and fschange::prev_thisfile.
Referenced by check_truncate().
fc_create_unlink()
static struct fschange * fc_create_unlink (struct fschange * prev_thisdir, struct fschange * prev_victimfile, unsigned dir, unsigned name, unsigned victimfile) static
Definition at line 391 of file check.c.
References fschange::dir, fc_create(), FC_UNLINK, fschange::fc_unlink, name, fschange::name, fschange::prev_thisdir, fschange::prev_victimfile, and fschange::victimfile.
Referenced by check_unlink(), and common_rename().
fc_create_write()
static struct fschange * fc_create_write (struct fschange * prev_thisfile, unsigned file, off_t pos, off_t len, off_t oldfilesize, unsigned code, unsigned seq) static
Definition at line 326 of file check.c.
References fschange::code, fc_create(), FC_WRITE, fschange::fc_write, fschange::file, fschange::len, fschange::oldfilesize, pos, fschange::pos, fschange::prev_thisfile, and fschange::seq.
Referenced by check_write().
finddir()
static struct fsobject * finddir (struct fsobject * rootdir, unsigned id) static
Definition at line 727 of file check.c.
References die(), findsub(), and NULL.
Referenced by apply_change(), model_finddir(), model_findfile(), model_findparent(), model_isdir(), and model_isfile().
findfile_maybe()
static struct fsobject * findfile_maybe (struct fsobject * rootdir, unsigned id) static
isdir
Definition at line 720 of file check.c.
References findsub().
Referenced by apply_change(), and model_getfilesize().
findokversion()
static unsigned findokversion (struct fschange * change) static
Definition at line 2263 of file check.c.
References assert, FC_TRUNCATE, FC_WRITE, NULL, fschange::prev, fschange::type, and fschange::version.
Referenced by checkonefilecontents().
findsub()
static struct fsobject * findsub (struct fsobject * obj, unsigned isdir, unsigned id) static
Definition at line 677 of file check.c.
References fsobject::entries, findsub(), fsobject::identity, isdir(), fsobject::isdir, fsdirent::next, NULL, fsdirent::obj, fsobject::obj_dir, and fsobject::obj_file.
Referenced by finddir(), findfile_maybe(), and findsub().
fsdir_add_entry()
static void fsdir_add_entry (struct fsobject * dir, struct fsdirent * nde) static
Definition at line 611 of file check.c.
References assert, die(), fsdirent::name, name_get(), fsdirent::next, and NULL.
Referenced by apply_change().
fsdir_find_entry()
static struct fsdirent * fsdir_find_entry (struct fsobject * dir, unsigned name, int croak) static
Definition at line 632 of file check.c.
References assert, die(), name, fsdirent::name, name_get(), fsdirent::next, and NULL.
Referenced by apply_change(), model_finddir(), model_findfile(), model_isdir(), and model_isfile().
fsdir_remove_entry()
static struct fsdirent * fsdir_remove_entry (struct fsobject * dir, unsigned name) static
Definition at line 654 of file check.c.
References assert, die(), name, fsdirent::name, name_get(), fsdirent::next, and NULL.
Referenced by apply_change().
fsdirent_create()
static struct fsdirent * fsdirent_create (unsigned name, struct fsobject * obj) static
Definition at line 479 of file check.c.
References getdirent(), name, fsdirent::name, fsdirent::next, NULL, and fsdirent::obj.
Referenced by apply_change(), and inspectdir().
fsdirent_destroy()
static void fsdirent_destroy (struct fsdirent * de) static
Definition at line 492 of file check.c.
References assert, fsdirent::next, NULL, fsdirent::obj, and putdirent().
Referenced by apply_change(), and fsobject_destroytree().
fsobject_create_dir()
static struct fsobject * fsobject_create_dir (unsigned id, struct fsobject * parent) static
Definition at line 515 of file check.c.
References fsobject::entries, getobject(), fsobject::identity, fsobject::isdir, NULL, fsobject::obj_dir, fsobject::parent, and fsobject::refcount.
Referenced by apply_change(), inspectdir(), and rewindstate().
fsobject_create_file()
static struct fsobject * fsobject_create_file (unsigned id) static
Definition at line 501 of file check.c.
References getobject(), fsobject::identity, fsobject::isdir, fsobject::len, fsobject::obj_file, and fsobject::refcount.
Referenced by apply_change(), and inspectdir().
fsobject_decref()
static void fsobject_decref (struct fsobject * obj) static
Definition at line 539 of file check.c.
References assert, fsobject::entries, fsobject::isdir, NULL, fsobject::obj_dir, putobject(), and fsobject::refcount.
Referenced by apply_change(), and fsobject_destroytree().
fsobject_destroytree()
static void fsobject_destroytree (struct fsobject * obj) static
Definition at line 555 of file check.c.
References fsobject::entries, fsdirent_destroy(), fsobject_decref(), fsobject_destroytree(), fsobject::isdir, fsdirent::next, NULL, fsdirent::obj, and fsobject::obj_dir.
Referenced by fsobject_destroytree(), and rewindstate().
fsobject_incref()
static void fsobject_incref (struct fsobject * obj) static
Definition at line 530 of file check.c.
References assert, and fsobject::refcount.
Referenced by apply_change().
getchange()
static struct fschange * getchange (void) static
Definition at line 241 of file check.c.
References POOLALLOC.
Referenced by fc_create().
getdirent()
static struct fsdirent * getdirent (void) static
Definition at line 255 of file check.c.
References POOLALLOC.
Referenced by fsdirent_create().
getobject()
static struct fsobject * getobject (void) static
Definition at line 248 of file check.c.
References POOLALLOC.
Referenced by fsobject_create_dir(), and fsobject_create_file().
inspectdir()
static struct fsobject * inspectdir (struct fsobject * parentobj, ino_t parentino, const char * dirnamestr) static
Definition at line 1896 of file check.c.
References assert, chdir(), close(), dirfd, fsobject::entries, err(), errx(), found_files, found_subdirs, fsdirent_create(), fsobject_create_dir(), fsobject_create_file(), getdirentry(), inspectdir(), fsobject::len, name_find(), NAME_MAX, fsdirent::next, NULL, O_RDONLY, fsobject::obj_dir, fsobject::obj_file, open(), S_ISDIR, stat::st_dev, stat::st_ino, stat::st_mode, stat::st_size, strcmp(), UNKNOWN_ID, and xstat().
Referenced by inspectdir(), and inspectfs().
inspectfs()
static void inspectfs (void) static
Definition at line 2016 of file check.c.
References err(), found, inspectdir(), NULL, stat::st_ino, and xstat().
Referenced by checkfs().
model_finddir()
static unsigned model_finddir (unsigned dirnum, unsigned name) static
Definition at line 1493 of file check.c.
References die(), finddir(), fsdir_find_entry(), fsobject::identity, fsobject::isdir, name, name_get(), fsdirent::obj, fsobject::obj_dir, and state.
Referenced by check_chdir(), check_renamexd(), check_rmdir(), and common_rename().
model_findfile()
static unsigned model_findfile (unsigned dirnum, unsigned name) static
Definition at line 1473 of file check.c.
References die(), finddir(), fsdir_find_entry(), fsobject::identity, fsobject::isdir, name, name_get(), fsdirent::obj, fsobject::obj_file, and state.
Referenced by check_link(), check_openfile(), check_unlink(), and common_rename().
model_findparent()
static unsigned model_findparent (unsigned dirnum) static
Definition at line 1513 of file check.c.
References assert, finddir(), fsobject::identity, fsobject::isdir, fsobject::obj_dir, fsobject::parent, and state.
Referenced by check_chdirup().
model_getfilesize()
static off_t model_getfilesize (unsigned filenum) static
Definition at line 1560 of file check.c.
References assert, findfile_maybe(), fsobject::isdir, fsobject::len, NULL, fsobject::obj_file, and state.
Referenced by check_write().
model_isdir()
static unsigned model_isdir (unsigned dirnum, unsigned name) static
Definition at line 1545 of file check.c.
References finddir(), fsdir_find_entry(), fsobject::isdir, name, NULL, fsdirent::obj, and state.
Referenced by common_rename().
model_isfile()
static unsigned model_isfile (unsigned dirnum, unsigned name) static
Definition at line 1529 of file check.c.
References finddir(), fsdir_find_entry(), fsobject::isdir, name, NULL, fsdirent::obj, and state.
Referenced by common_rename().
printdiffs()
static void printdiffs (unsigned indent, struct fsobject * obja, struct fsobject * objb) static
Definition at line 2163 of file check.c.
References assert, count_subtree(), doindent(), fsobject::entries, found, fsobject::isdir, fsobject::len, fsdirent::name, name_get(), fsdirent::next, NULL, fsdirent::obj, fsobject::obj_dir, fsobject::obj_file, printdiffs(), and printf().
Referenced by checkfs(), and printdiffs().
putdirent()
static void putdirent (struct fsdirent * dirent) static
Definition at line 278 of file check.c.
References POOLFREE.
Referenced by fsdirent_destroy().
putobject()
static void putobject (struct fsobject * obj) static
Definition at line 271 of file check.c.
References fsdirent::obj, and POOLFREE.
Referenced by fsobject_decref().
readfiledata()
static void readfiledata (int fd, const char * namestr, off_t regionstart, off_t checkstart, off_t checkend, off_t regionend) static
Definition at line 2385 of file check.c.
References assert, data_mapreadbuf(), err(), errx(), fd, fschange::len, lseek(), read(), readbuf, and SEEK_SET.
Referenced by change_is_present(), and checkfiledata().
rewindstate()
static void rewindstate (void) static
Definition at line 962 of file check.c.
References assert, FC_NEWFS, fschange::fc_newfs, firstchange, fsobject_create_dir(), fsobject_destroytree(), NULL, fsobject::obj_dir, fsobject::parent, fschange::rootdirnum, state, and fschange::type.
Referenced by check_setup(), and checkfs().
xstat()
static int xstat (const char * path, struct stat * buf) static
Definition at line 1871 of file check.c.
References buf, close(), errno, fd, fstat(), O_RDONLY, and open().
Referenced by inspectdir(), and inspectfs().
Variable Documentation
changes
struct fschange* changes static
Definition at line 914 of file check.c.
Referenced by changes_findprevdir(), changes_findprevfile(), check_setup(), checkfs(), and fc_attach().
cwd
unsigned cwd static
Definition at line 1577 of file check.c.
Referenced by check_chdir(), check_chdirup(), check_createfile(), check_link(), check_mkdir(), check_openfile(), check_rename(), check_renamexd(), check_rmdir(), check_setup(), check_unlink(), and vfs_getcwd().
firstchange
struct fschange* firstchange static
Definition at line 913 of file check.c.
Referenced by advancestateto(), check_setup(), checkfs(), and rewindstate().
found
struct fsobject* found static
Definition at line 1860 of file check.c.
Referenced by checkfs(), compare_objects(), findmount(), hangman_check(), inspectfs(), printdiffs(), and sfs_dir_findname().
found_files
unsigned found_files static
Definition at line 1863 of file check.c.
Referenced by checkfs(), and inspectdir().
found_subdirs
unsigned found_subdirs static
Definition at line 1863 of file check.c.
Referenced by checkfs(), and inspectdir().
nextdirnum
unsigned nextdirnum static
Definition at line 929 of file check.c.
Referenced by check_mkdir(), check_setup(), and checkfs().
nextfilenum
unsigned nextfilenum static
Definition at line 929 of file check.c.
Referenced by check_createfile(), check_setup(), check_truncate(), check_write(), and checkfs().
state
struct fsobject* state static
Definition at line 922 of file check.c.
Referenced by advancestateto(), check_setup(), checkfs(), fc_attach(), model_finddir(), model_findfile(), model_findparent(), model_getfilesize(), model_isdir(), model_isfile(), and rewindstate().