os161-doc: /home/parallels/os161/os161-base-2.0.3/userland/lib/libc/stdlib/getenv.c File Reference
getenv.c File Reference
#include <stdlib.h>
#include <string.h>
Functions
char * getenv (const char *var)
Variables
char ** __environ
static const char * __default_environ []
Function Documentation
getenv()
char * getenv (const char * var)
Definition at line 56 of file getenv.c.
References __default_environ, __environ, memcmp(), NULL, strchr(), and strlen().
Referenced by execvp().
Variable Documentation
__default_environ
const char* __default_environ[] static
Initial value:
= {
    "PATH=/bin:/sbin:/testbin",
    "SHELL=/bin/sh",
    "TERM=vt220",
    NULL
}
Definition at line 48 of file getenv.c.
Referenced by getenv().
__environ
char** __environ extern
Definition at line 43 of file errno.c.
Referenced by getenv().