os161-doc: /home/parallels/os161/os161-base-2.0.3/common/libc/string/strchr.c File Reference
strchr.c File Reference
#include <string.h>
Functions
char * strchr (const char *s, int ch_arg)
Function Documentation
strchr()
char * strchr (const char * s, int ch_arg)
Definition at line 47 of file strchr.c.
References ch, and NULL.
Referenced by __pf_send(), atoi(), execvp(), getenv(), main(), main(), strtok_r(), and vfs_setbootfs().